namespace MetroAutomation.Automation
{
    public enum AutomationMode
    {
        GetDCV,
        SetDCV,
        GetACV,
        SetACV,
        GetDCI,
        SetDCI,
        GetACI,
        SetACI,
        GetRES2W,
        SetRES2W,
        GetRES4W,
        SetRES4W,
        GetCAP2W,
        SetCAP2W,
        GetCAP4W,
        SetCAP4W,
        GetIND2W,
        SetIND2W,
        GetIND4W,
        SetIND4W,
        GetADM4W,
        SetADM4W,
        GetDCP,
        SetDCP,
        GetACP,
        SetACP,
        SetDCV_DCV,
        SetACV_ACV,
        GetTEMP,
        SetTEMP,
        GetFREQ,
        SetFREQ
    }
}
